export const mockDataResponse = {
  data: {
    tradingPairs: [
      {
        displaySymbol: 'BTC-CAD',
        baseCurrency: 'BTC',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: {
          high: '14250',
          low: '14200',
          close: '14200',
          average: '14225',
          percentChange: '-0.35087719298245614000',
          orderbook: {
            asks: [{ price: '20000' }, { price: '70000' }, { price: '75000' }],
            bids: [
              { price: '14200' },
              { price: '14100' },
              { price: '14000' },
              { price: '13900' },
              { price: '1000' },
              { price: '450' },
              { price: '200' },
              { price: '100' },
              { price: '22' },
              { price: '20' },
              { price: '12' },
              { price: '10' },
              { price: '1.23' },
              { price: '1' },
            ],
            spread: '5800',
          },
        },
      },
      {
        displaySymbol: 'ETH-CAD',
        baseCurrency: 'ETH',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: {
          high: '560',
          low: '560',
          close: '560',
          average: '560',
          percentChange: '0',
          orderbook: {
            asks: [],
            bids: [{ price: '560' }, { price: '558' }, { price: '400' }],
            spread: null,
          },
        },
      },
      {
        displaySymbol: 'XLM-CAD',
        baseCurrency: 'XLM',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'BSV-CAD',
        baseCurrency: 'BSV',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'DASH-CAD',
        baseCurrency: 'DASH',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'XRP-CAD',
        baseCurrency: 'XRP',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'BCH-CAD',
        baseCurrency: 'BCH',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'LTC-CAD',
        baseCurrency: 'LTC',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'DOGE-CAD',
        baseCurrency: 'DOGE',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'ETC-CAD',
        baseCurrency: 'ETC',
        quoteCurrency: 'CAD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'BTC-USD',
        baseCurrency: 'BTC',
        quoteCurrency: 'USD',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'ETH-BTC',
        baseCurrency: 'ETH',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: {
          high: '0.04',
          low: '0.04',
          close: '0.04',
          average: '0.04',
          percentChange: '0',
          orderbook: {
            asks: [],
            bids: [{ price: '0.00011' }],
            spread: null,
          },
        },
      },
      {
        displaySymbol: 'XLM-BTC',
        baseCurrency: 'XLM',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'BSV-BTC',
        baseCurrency: 'BSV',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'DASH-BTC',
        baseCurrency: 'DASH',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'XRP-BTC',
        baseCurrency: 'XRP',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'BCH-BTC',
        baseCurrency: 'BCH',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'LTC-BTC',
        baseCurrency: 'LTC',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'DOGE-BTC',
        baseCurrency: 'DOGE',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: null,
      },
      {
        displaySymbol: 'ETC-BTC',
        baseCurrency: 'ETC',
        quoteCurrency: 'BTC',
        marketDataLast24HourPriceAggregate: null,
      },
    ],
  },
}
